import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Header from "@/components/Header";
import FooterHandler from "@/components/FooterHandler";
import { WishlistProvider } from "@/app/context/WishlistContext"; // Import WishlistProvider

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <WishlistProvider> {/* Wrap your app in WishlistProvider */}
          <Header />
          {children}
          <FooterHandler />
        </WishlistProvider>
      </body>
    </html>
  );
}
